name: mswin
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  mswin:
    strategy:
      matrix:
        vs: [2022]
      fail-fast: false
    runs-on: windows-${{ matrix.vs }}
    env:
      PRE: Ruby31-ms
      RUBY_FILENAME: Ruby-3.1.3-ms
      TAG: v3_1_3

    steps:
      - name: git config
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: repo checkout
        uses: actions/checkout@v3

      - name: get ruby and rubyinstaller2
        timeout-minutes: 5
        run: |
          $gh = 'https://github.com'
          git clone -q --depth=1 --no-tags --branch=master   $gh/oneclick/rubyinstaller2.git ./rubyinstaller2
          git clone -q --depth=1 --no-tags --branch=$env:TAG $gh/ruby/ruby.git               ./ruby

      - name: load ruby
        timeout-minutes: 12
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: mswin

      - name: Cache - .downloaded-cache
        uses: actions/cache@v3
        with:
          path: .downloaded-cache
          key: dl-cache-win-${{ env.TAG }}-${{ hashFiles('ruby/gems/bundled_gems') }}

      - name: build & install
        timeout-minutes: 30
        run:  ./1_0_build_install_mswin.ps1

      - name: test
        timeout-minutes: 70
        run:  ./2_0_test.ps1 mswin
        env:
          APPVEYOR: 'True'

      - name: CLI Check Bash
        shell: bash
        run: ./cli_test_bash

      - name: upload 7z archive
        timeout-minutes: 10
        run:  ruby upload_build.rb create_asset
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: save log artifact
        if: success() || failure()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.TEST_LOGS }}
          path: ./logs
